package org.zhj.easychat.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHAT_MESSAGE.
 */
public class ChatMessage {

    private Long id;
    /** Not-null value. */
    private String peerId;
    /** Not-null value. */
    private String otherPeerId;
    private boolean isFrom;
    /** Not-null value. */
    private String msg;
    private long timestamp;

    public ChatMessage() {
    }

    public ChatMessage(Long id) {
        this.id = id;
    }

    public ChatMessage(Long id, String peerId, String otherPeerId, boolean isFrom, String msg, long timestamp) {
        this.id = id;
        this.peerId = peerId;
        this.otherPeerId = otherPeerId;
        this.isFrom = isFrom;
        this.msg = msg;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPeerId() {
        return peerId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPeerId(String peerId) {
        this.peerId = peerId;
    }

    /** Not-null value. */
    public String getOtherPeerId() {
        return otherPeerId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOtherPeerId(String otherPeerId) {
        this.otherPeerId = otherPeerId;
    }

    public boolean getIsFrom() {
        return isFrom;
    }

    public void setIsFrom(boolean isFrom) {
        this.isFrom = isFrom;
    }

    /** Not-null value. */
    public String getMsg() {
        return msg;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

}
