package org.zhj.easychat.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table FRIEND.
 */
public class Friend {

    private Long id;
    private String peerId;
    private String friendPeerId;

    public Friend() {
    }

    public Friend(Long id) {
        this.id = id;
    }

    public Friend(Long id, String peerId, String friendPeerId) {
        this.id = id;
        this.peerId = peerId;
        this.friendPeerId = friendPeerId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPeerId() {
        return peerId;
    }

    public void setPeerId(String peerId) {
        this.peerId = peerId;
    }

    public String getFriendPeerId() {
        return friendPeerId;
    }

    public void setFriendPeerId(String friendPeerId) {
        this.friendPeerId = friendPeerId;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null) {
            return false;
        }
        if (o == this) {
            return true;
        }
        if (o instanceof Friend) {
            Friend friend = (Friend) o;
            if (friend.peerId.equals(peerId) && friend.friendPeerId.equals(friendPeerId)) {
                return true;
            }
        }
        return false;
    }
}
