package org.zhj.easychat.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String peerId;
    private String avatarUrl;
    private String introduction;
    private String gender;
    private String area;
    private String nickname;
    private String interest;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String peerId, String avatarUrl, String introduction, String gender, String area, String nickname, String interest) {
        this.id = id;
        this.peerId = peerId;
        this.avatarUrl = avatarUrl;
        this.introduction = introduction;
        this.gender = gender;
        this.area = area;
        this.nickname = nickname;
        this.interest = interest;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPeerId() {
        return peerId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPeerId(String peerId) {
        this.peerId = peerId;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public String getIntroduction() {
        return introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getInterest() {
        return interest;
    }

    public void setInterest(String interest) {
        this.interest = interest;
    }

}
